# Generated by Django 5.2.7 on 2025-11-03 21:22

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detailed_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Детальний опис товару з форматуванням (CKEditor)'),
        ),
    ]
